services:
  - type: web
    name: little-souls-backend
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 3000
