-- AlterTable
ALTER TABLE "products" ADD COLUMN     "colors" TEXT,
ADD COLUMN     "colors_set_quantity" INTEGER,
ADD COLUMN     "discounted_price" DECIMAL(12,2),
ADD COLUMN     "nt11_48" TEXT,
ADD COLUMN     "nt11_48_set_quantity" INTEGER,
ADD COLUMN     "parent_product_id" TEXT,
ADD COLUMN     "parent_product_sku" TEXT,
ADD COLUMN     "private_notes" TEXT,
ADD COLUMN     "product_image" TEXT,
ADD COLUMN     "product_picture_url" TEXT,
ADD COLUMN     "product_price" DECIMAL(12,2),
ADD COLUMN     "set_name" TEXT,
ADD COLUMN     "set_quantity" INTEGER,
ADD COLUMN     "set_type" TEXT,
ADD COLUMN     "six_to_twelve_months" TEXT,
ADD COLUMN     "six_to_twelve_months_set_quantity" INTEGER,
ADD COLUMN     "sizes" TEXT,
ADD COLUMN     "sizes_set_quantity" INTEGER,
ADD COLUMN     "tax_type" TEXT;
